### ISSUE TITLE
Followed all instructions and post CMAKE, make -j does nothing, no error

### ISSUE THREAD

**Issue by sleeplessTLV** [wangyiqiu/dbscan-python#14]
Hi,
finally compiled binary dbscan and can run it.
The sample file given in the tutorial is 40 lines long. When I run with it and eps 0.1, minpts 10 dbscan runs and outputs all points as outliers. Is this OK?
thanks!

**Comment by sleeplessTLV** [comment]
With larger EPS, smaller Minpts one can get clustering.

**Comment by wangyiqiu** [comment]
Hi @sleeplessTLV 
For some data sets a suitable set of parameter needs to be chosen to cluster properly.
Feel free to share the data set and parameter where you got errors and I can take a look.

**Comment by sleeplessTLV** [comment]
Dear Dr. Wang,
in the end we managed to set relevant eps and minpts values for this
dataset and got good clustering.
Sorry for bothering you. We will now proceed to try on more heavy datasets.
Thank you very much for the prompt response!
BR
Tsvi

**Comment by sleeplessTLV** [comment]
Dear Dr. Wang,
in the github code, it is not clear to us if/how the various modes of
BCP/Delaunay/USEC can be used or just one? And same question for grid vs
box?
thanks
Tsvi

**Comment by wangyiqiu** [comment]
Hi @sleeplessTLV 
Glad that you got the parameter working. No problem - I will be happy to answer your questions.
This dbscan-python repository was re-written later, and is slightly different from our code for the paper.

The code for the paper is here: https://github.com/wangyiqiu/dbscan
The reproducibility instructions are here: https://github.com/wangyiqiu/dbscan-reproducibility
More specifically, to switch among different methods, please refer to the instructions here: https://github.com/wangyiqiu/dbscan

I will have to dig a little bit to find the code that switches among BCP/Delaunay/USEC, grid/box. Hopefully the links above are helpful to you.

**Comment by sleeplessTLV** [comment]
Thanks a lot! Very helpful.
