### ISSUE TITLE
Large N Overflows

### ISSUE THREAD

**Issue by william-silversmith** [wangyiqiu/dbscan-python#17]
Hi! 

I'm working with a very large dataset of over 100M points and this implementation is working beautifully except for the documented warning.

"Large n, the program behavior might be undefined due to overflow"

This causes clusters to appear that are very distant from each other. Is there any way to improve this behavior? I can clean this up by thresholding dust, but there are some manual operations I can't do that would make my segmentation much nicer due to this problem.

Thank you so much for this wonderful DBSCAN implementation. I wouldn't be complaining if it wasn't capable of handling such a huge number of points already!

**Comment by william-silversmith** [comment]
I might be able to do some debugging and try to expand the range. Does it have something to do with intT/uintT being defined as a 32-bit integer? Thanks again for any tips!

**Comment by wangyiqiu** [comment]
Hi! Thanks for your interest.
Could you elaborate on "causes clusters to appear that are very distant from each other"?
From the description it may or may not be caused by large N overflows. I would expect when an overflow happens, a segmentation fault will occur.

Yes, the 32-bit integers used in the code could potentially be the culprit of an overflow.

**Comment by william-silversmith** [comment]
Hi! Thanks so much for your response. I can illustrate this with a picture. I divided the data in two so now it is less than 100M and I am still seeing this kind of issue.

The below image is a section of a larger 3D image. Here you can see in white, set of selected segments. Surrounding the segments are the rest of the samples from a brain. I was careful to only select elements from the right hand structure (the medulla).

<img width="619" alt="image" src="https://github.com/wangyiqiu/dbscan-python/assets/2517065/26650eac-94fd-4502-9335-ac00ce1dc03c">

In this second view, I have changed the visualization mode so that unselected elements are colored as background while selected elements are colored from one of a palette of colors. In this view, it is clear that there are clusters spanning the entire dataset, but they have no plausible linkage between them.

<img width="644" alt="image" src="https://github.com/wangyiqiu/dbscan-python/assets/2517065/02c4b4de-e02b-4de6-85be-f0c6eb3481b1">

If I delete the dust on the left hand side, it erodes the selections I've made on the right-hand side. 

Here is how I am invoking DBSCAN:

```python
from dbscan import DBSCAN
import numpy as np
from cloudvolume import CloudVolume
import time
import microviewer
import fastremap

data = np.load("data.npy")
post = data[:,1]

sample_factor = 2
post = post[::sample_factor]
post = np.asfortranarray(post)

s = time.time()
labels, core_samples_mask = DBSCAN(
    post, eps=725, min_samples=9
)
print(f"DBSCAN completed in {time.time() - s:.1f} sec.")

colorized = np.lib.format.open_memmap(
    f"clusters.npy", 
    shape=(shape[0], shape[1], shape[2]), 
    dtype=np.uint16,
    fortran_order=True,
    mode="w+"
)

colorized[post[:,0], post[:,1], post[:,2]] = labels
colorized = fastremap.mask(colorized, [ np.iinfo(np.uint16).max ], in_place=True)

microviewer.view(colorized, seg=True, browser=True)
```

**Comment by william-silversmith** [comment]
My apologies, I figured it out. The problem was my fault, there was an overflow due to the use of uint16 instead of uint32 in the rendered image. Your code is fine. I hope I didn't waste too much of your time. Thank you for reading and providing such a wonderful library!

**Comment by wangyiqiu** [comment]
Hi @william-silversmith I am glad the problem is resolved. Please let me know if you have further questions!
