### ISSUE TITLE
Cannot import in Conda environment

### ISSUE THREAD

**Issue by zp-yang** [wangyiqiu/dbscan-python#5]
In my conda environment:
`>>> import dbscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zpyang/anaconda3/envs/visnet/lib/python3.9/site-packages/dbscan/__init__.py", line 22, in <module>
    from dbscan.DBSCAN import DBSCAN
ModuleNotFoundError: No module named 'dbscan.DBSCAN'
`
but it is successfully imported while outside the conda environment. Not sure why that's the case.

**Comment by wangyiqiu** [comment]
Hi, thanks for the feedback. We have not tested the software in a Conda environment before. Could you let us know the system environment and Conda version that you are using?

**Comment by zp-yang** [comment]
I am using Ubuntu 20.04, conda 4.10.3, and python 3.9.7. Installed in dbscan using pip in conda environment. Hope this is useful. I also tried to build from source in conda environment but that didn't work as well.

**Comment by anivegesana** [comment]
@wangyiqiu Although I closed this before because the pip package now installs correctly in conda environments, maybe it is a good idea to reopen it. It might be a good idea to add the package to `conda-forge` so that it can be installed as a conda package.

The process doesn't seems to be difficult and it would be useful for people who want to avoid conflicts between a conda and pip version of numpy. I'll look into it more in the near future.

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by anivegesana** [comment]
Hey @wangyiqiu. Created a conda recipe here: conda-forge/staged-recipes#22009

Do not know if you had time to look at it yet. When you have time, respond to that thread saying that you are willing to be a maintainer for the conda package.

**Comment by anivegesana** [comment]
Alright. The conda package can be downloaded with the following command:
```sh
conda install -c conda-forge dbscan
```
I think to update the conda package, we just create a PR that increments the [`version`](https://github.com/conda-forge/dbscan-feedstock/blob/main/recipe/meta.yaml#L6) and update the [`sha256`](https://github.com/conda-forge/dbscan-feedstock/blob/main/recipe/meta.yaml#L10) with the value that shows up under ["view hashes" on PyPI](https://pypi.org/project/dbscan/#files), but I think there is a bot that does that. So the only real work we need to do is pull the PRs created by [regro-cf-autotick-bot](https://github.com/regro-cf-autotick-bot). I will look into it further to make sure that there isn't anything else that needs to be done.
https://conda-forge.org/docs/maintainer/updating_pkgs.html

**Comment by wangyiqiu** [comment]
Looks great, thanks @anivegesana for working on this!
I will also verify the package in conda when I get to it.
