### ISSUE TITLE
dbscan result is wrong with  the latest two commits

### ISSUE THREAD

**Issue by sun11** [wangyiqiu/dbscan-python#6]
I used `src/make.sh` to compile the code and generated *.so file successfully, but got a wrong clustering result.
![img_v2_96c4c8a6-a8c6-4168-aa6f-b2432bb8a1eg](https://user-images.githubusercontent.com/994030/147821736-7011ab54-17ca-422a-9753-44347fdf1e86.png)

The commit [646cc6](https://github.com/wangyiqiu/dbscan-python/commit/646cc6883825ccecb0a672374f4b019bed6845d4) and [08dd4a](https://github.com/wangyiqiu/dbscan-python/commit/08dd4a443f09572666343bcfe300576f207e6b3d) has the same wrong results.

But I found https://github.com/wangyiqiu/dbscan-python/commit/83c56964326150d19a48e19fc97b5a0e0b3ee89d which produced `example.png` can generate right result, but it seems to have memory leak issues.

Edit: The latest commit which work normally is [8c6afc](https://github.com/wangyiqiu/dbscan-python/commit/8c6afc4d40fe3cf25de954de3ad6609b866a6b4b)

**Comment by wangyiqiu** [comment]
Hi, thanks for spotting the bug.

A [recent commit](https://github.com/wangyiqiu/dbscan-python/commit/1fe10f03fe7a02113ff8fd99e25ba34f43b97f8d) caused this error, and it has been correct [here](https://github.com/wangyiqiu/dbscan-python/commit/ae3860cc965314adb819c02d9c3af831b183dd98).

I regenerated `example.png` and it seems to be correct now.

**Comment by sun11** [comment]
It now works normally. Thank you for your reply. 👍️

**Comment by wangyiqiu** [comment]
Hi, I just pushed another related fix. Please update your local copy if necessary. Thank you for spotting the bug. I now believe it has been fully fixed.
