### ISSUE TITLE
Parallel Approximate DBSCAN Clustering 

### ISSUE THREAD

**Issue by amir-keramatian** [wangyiqiu/dbscan-python#7]
Does this repository support parallel approximate DBSCAN clustering? If so, please instruct me on how to use it. Thank you.

**Comment by wangyiqiu** [comment]
Hi, thanks for your interest. This repository does not contain the parallel approximate DBSCAN code, but you could refer to our [research code repository](https://github.com/wangyiqiu/dbscan) for the parallel approximate DBSCAN code. 

Specifically, there's a [tutorial](https://github.com/wangyiqiu/dbscan/blob/master/code/README.md) for running the code. The default method used is exact DBSCAN, but you can switch to the approximate version by commenting out [this line](https://github.com/wangyiqiu/dbscan/blob/efa05c7501be5712e6a0b1b6805f0f854fc36244/code/DBSCAN.C#L3) and uncommenting [this line](https://github.com/wangyiqiu/dbscan/blob/efa05c7501be5712e6a0b1b6805f0f854fc36244/code/DBSCAN.C#L5) prior to compilation.

**Comment by amir-keramatian** [comment]
Thank you for the information.
